#**1.Версия Pandas**

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
!pip show pandas

Name: pandas
Version: 1.3.5
Summary: Powerful data structures for data analysis, time series, and statistics
Home-page: https://pandas.pydata.org
Author: The Pandas Development Team
Author-email: pandas-dev@python.org
License: BSD-3-Clause
Location: /usr/local/lib/python3.7/dist-packages
Requires: pytz, numpy, python-dateutil
Required-by: xarray, vega-datasets, statsmodels, sklearn-pandas, seaborn, pymc3, plotnine, pandas-profiling, pandas-gbq, pandas-datareader, mlxtend, mizani, holoviews, gspread-dataframe, google-colab, fix-yahoo-finance, fbprophet, fastai, cufflinks, cmdstanpy, arviz, altair


In [ ]:
pd.__version__

'1.3.5'

In [ ]:
np.__version__

'1.21.6'

#**2.Особенность контейнера Pandas`а. Series**

**Numpy хорошо работает с числовыми данными - для этого он и создавался. Но на практике таблицы содержат не только числа, но и текст. Поэтому пришлось создавать другие контейнеры данных, которые хорошо будут работать с другими типами.**

**Series (серия или по простому ряд значений) - контейнер в библиотеке Pandas, который создан для хранения одномерного массива данных. В нее нельзя погрузить матрицу или трехмерный массив. Серия может унести только одномерный массив. Именно серия будет хранить содержимое наших столбцов и строк поэтому давайте посмотрим на нее подробнее.**

**Серия состоит из двух очень важных компонентов:**

1. хранилище наших значений (именно эти значения мы видим в столбце/строке)

2. хранилище индексов. Индексы могут быть как числовые так и строковые. Обращаясь к серии через индекс мы просим серию вернуть из хранилища значений элемент, который связан с индексом. Очень похоже на словарь! 

**Индексы и значения жестко связаны между собой.**

In [9]:
# реализация словаря
d = {'a': 1, 'b': 3, 'c': 10}
d['c']

10

**Чтобы создать серию вам надо обратиться к библиотеке pandas и у неё спросить серию: pandas.Series(). В скобки передайте одномерный список или массив. Кстати, словарь тоже сработает! Pandas примет ваш массив/словарь и создаст на их основе серию.**

При попытке распечатать на экране серию, питон печатает две колонки: левая - индексы, правая - наши значения.

- Через свойство .index вы получите одномерный numpy массив индексов

- Через свойство .values вы получите одномерный numpy массив с нашими значениями

In [10]:
import pandas as pd

In [12]:
pd.Series(np.arange(10))

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64

In [17]:
s1 = pd.Series([1, 3, 5, 6, 8])

In [18]:
s1

0    1
1    3
2    5
3    6
4    8
dtype: int64

In [22]:
s1.values

array([1, 3, 5, 6, 8])

In [25]:
s1.index

RangeIndex(start=0, stop=5, step=1)

**Если при создании серии вы не задаёте индексы, то серия автоматически создает их для себя. Вы можете задать свои индексы, для этого в конструктор серии передайте значения, которые надо хранить в серии и индексы для них.**



In [28]:
s2 = pd.Series([1, 3, 5, 6, 7], index=['a', 'b', 'c', 'd', 'e'])
s2

a    1
b    3
c    5
d    6
e    7
dtype: int64

In [29]:
s2.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

**Для доступа к элементу серии в скобках укажите индекс, который связан с этим элементом. Если индекс числовой, то в квадратных скобках укажите число: s[1]. Если индексы строковые, то укажите в кавычках: s["c"] (можно одинарные, можно двойные).**

In [30]:
s2['c']

5

In [33]:
s2[s2.index == 'c']

c    5
dtype: int64

In [35]:
s2[2]

5

In [36]:
s2[s2.index == 2]

Series([], dtype: int64)

**Вы можете создавать серию как на основе списка, так и на основе numpy массива - результат будет одинаковый)Для получения доступа к нескольким элементам серии передайте список индексов: s[['a', 'b', 'c']]**

In [37]:
s2['c'] = -5
s2

a    1
b    3
c   -5
d    6
e    7
dtype: int64

In [39]:
s2[['b', 'd']]

b    3
d    6
dtype: int64

In [40]:
s2.values

array([ 1,  3, -5,  6,  7])

In [41]:
s2.values.dtype

dtype('int64')

In [43]:
s3 = pd.Series([1.5, 2, 3.2, 6])
s3.values.dtype

dtype('float64')

In [50]:
s3 = pd.Series(np.random.randint(1, 10, 10))
s3

0    2
1    7
2    2
3    8
4    6
5    4
6    3
7    3
8    1
9    8
dtype: int64

**Создайте серию, которая будет содержать элементы 1, 2, 3, 4, 5. Функция должна вернуть серию**

In [51]:
import pandas as pd
import numpy as np

def solution():
    result = pd.Series(np.arange(1, 6, 1))
    return result

solution()

0    1
1    2
2    3
3    4
4    5
dtype: int64

**На вход функции подаётся серия. Доработайте функцию так чтобы она возвращала индексы серии**



In [53]:
import numpy as np
import pandas as pd

def solution(s1):
    return s1.index

s1 = pd.Series(np.arange(10))
solution(s1)

RangeIndex(start=0, stop=10, step=1)

**Создайте серию, которая будет содержать элементы 1, 2, 3, 4, 5 и индексы a, b, c, d, e. Функция должна вернуть серию.**

In [55]:
import numpy as np
import pandas as pd

def solution():
    return pd.Series(np.arange(1, 6), index=['a', 'b', 'c', 'd', 'e'])

solution()

a    1
b    2
c    3
d    4
e    5
dtype: int64

**На вход функции подаётся серия. Вытяните из нее элементы с индексами a и с. Функция должна вернуть серию.**



In [56]:
import numpy as np
import pandas as pd

def solution(s1):
    result = s1[['a', 'c']]
    return result

s1 = pd.Series(np.arange(1, 6), index=['a', 'b', 'c', 'd', 'e'])
solution(s1)

a    1
c    3
dtype: int64

**На вход функции подаётся серия. Замените элемент по индексу c на 0. Функция должна вернуть серию с измененным элементом по индексу с.**



In [57]:
import numpy as np
import pandas as pd

def solution(s1):
    s1['c'] = 0
    return s1

s1 = pd.Series(np.arange(1, 6), index=['a', 'b', 'c', 'd', 'e'])
solution(s1)

a    1
b    2
c    0
d    4
e    5
dtype: int64

**На вход функции подаётся серия. Доработайте функцию так чтобы она возвращала numpy массив, который содержит значения серии**



In [58]:
import numpy as np
import pandas as pd

def solution(s1):
    return s1.values

s1 = pd.Series(np.arange(10))
solution(s1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])