**На выход подаётся матрица. Выполните ее транспонирование, а затем выполните возведение в квадрат каждого значения.**



In [3]:
import numpy as np

def solution(arr):
    return arr.T**2

arr = np.random.randint(0, 10, (3, 6))
print(arr)
print(solution(arr))

[[0 2 6 5 4 3]
 [2 7 1 2 3 9]
 [9 9 6 8 4 3]]
[[ 0  4 81]
 [ 4 49 81]
 [36  1 36]
 [25  4 64]
 [16  9 16]
 [ 9 81  9]]


**На вход подаётся матрица. Вытяните первую и последнюю строчки. Сравните поэлементно две строчки и постройте новый одномерный массив, который будет состоять из минимальных значений. Например, если первый элемент первой строки больше чем первый элемент последней строки, то в результат должен пойти первый элемент последней строки. Тоже проделайте с остальными элементами.**

In [4]:
import numpy as np

def solution(arr):
    res = np.minimum(arr[0], arr[-1])
    return res


arr = np.random.randint(0, 10, (4, 6))
print(arr)
print(solution(arr))

[[2 6 4 6 3 9]
 [7 8 0 1 6 7]
 [3 9 1 0 0 2]
 [3 9 7 5 8 6]]
[2 6 4 5 3 6]


**Прежде чем применять бинарную функцию на двух массивах, вы должны быть уверены, что ваши массивы имеют одинаковую размерность. На вход вашей функции подаётся два контейнера. Проверьте, равны ли размерности. Функция должна вернуть True, если размерности равны и False если нет.**

Попробуйте оттолкнуться от свойства shape. Посмотрите какие длины у кортежей и что за значения внутри них.

In [7]:
import numpy as np

def solution(a1, a2):
    result = a1.shape == a2.shape
    return result

a1 = np.random.randint(0, 10, (4, 6))
a2 = np.random.randint(0, 10, (4, 6))
solution(a1, a2)

True