In [1]:
import numpy as np

m1 = np.array([1, 2, 3, 4])
m2 = np.array([0, 3, 1, 6])

#**Функиции greater, less, equal**

Возвращает маску

In [2]:
# строго больше
np.greater(m1, m2)

array([ True, False,  True, False])

In [3]:
m1 >= m2

array([ True, False,  True, False])

In [4]:
np.greater_equal(m1, m2)

array([ True, False,  True, False])

In [5]:
# строго меньше
np.less(m1, m2)

array([False,  True, False,  True])

In [6]:
np.less_equal(m1, m2)

array([False,  True, False,  True])

In [7]:
m1 == m2

array([False, False, False, False])

In [8]:
np.equal(m1, m2)

array([False, False, False, False])

#**Вложенность функций**

In [11]:
m3 = np.minimum(m1, m2)
np.abs(m3)

array([0, 2, 1, 4])

In [12]:
m3 = np.abs(np.minimum(m1, m2))
m3

array([0, 2, 1, 4])

In [14]:
np.round(np.sqrt(m1**2 + m2**3), 3)

array([ 1.   ,  5.568,  3.162, 15.232])

#**Немного статистики. Функция where.**

In [18]:
m1 = np.array([2, -3, 4, -6, 7, -8])
mask1 = m1 > 0

In [19]:
mask2 = m1 < 0

In [21]:
m1[mask1] = 100
m1[mask2] = -100
m1

array([ 100, -100,  100, -100,  100, -100])

In [22]:
m1 = np.array([2, -3, 4, -6, 7, -8])
np.where(m1 > 0, 100, -100)

array([ 100, -100,  100, -100,  100, -100])

In [23]:
np.where(m1 < 0, 0, m1)

array([2, 0, 4, 0, 7, 0])

In [24]:
np.where(m1 > 0, m1**2, m1)

array([ 4, -3, 16, -6, 49, -8])

In [25]:
np.where(m1 < 0, np.abs(m1), m1)

array([2, 3, 4, 6, 7, 8])

In [26]:
np.where((m1 == 2) | (m1 == -3), -100, m1)

array([-100, -100,    4,   -6,    7,   -8])

In [28]:
m2d = np.arange(20).reshape(5, 4)
m2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [29]:
np.where(m2d < 10, 0, m2d)

array([[ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

#**Статистические функции**

In [30]:
m1 = np.arange(6)
m1

array([0, 1, 2, 3, 4, 5])

In [31]:
np.sum(m1)

15

In [32]:
np.mean(m1)

2.5

In [33]:
m1.sum()

15

In [34]:
m1.mean()

2.5

In [35]:
m2d = np.arange(12).reshape(2, 6)
m2d

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [37]:
m2d.sum()

66

In [38]:
m2d[0].sum()

15

In [40]:
#По строкам
m2d.sum(axis=1)

array([15, 51])

In [42]:
#По столбцам
m2d.sum(axis=0)

array([ 6,  8, 10, 12, 14, 16])

In [46]:
m2d.min(axis=0)

array([0, 1, 2, 3, 4, 5])

In [45]:
m2d.max(axis=1)

array([ 5, 11])

In [47]:
m2d.std()

3.452052529534663

In [48]:
m2d.var()

11.916666666666666

In [51]:
m1 = np.array([0, 1, -2, 0, 5, 6])
#индекс минимального значения
m1.argmin()

2

In [52]:
#индекс максимального значения
m1.argmax()

5

In [54]:
bools_arr = np.array([True, True, False, True])
bools_arr

array([ True,  True, False,  True])

In [55]:
bools_arr.sum()

3

**На вход подаётся два одномерных массива. Сравните их поэлементно: постройте новый массив из минимальных значений. У нового одномерного массива найдите максимальное значение**

In [58]:
import numpy as np

def solution(m1, m2):
    result = np.minimum(m1, m2).max()
    return result

m1 = np.random.randint(0, 10, 10)
m2 = np.random.randint(0, 10, 10)
print(m1)
print(m2)
solution(m1, m2)

[4 5 4 5 0 2 8 7 0 5]
[5 8 0 5 3 8 9 5 6 0]


8

**На вход подаётся два одномерных массива. Сравните их поэлементно. Постройте новый массив из максимальных значений. У нового одномерного массива найдите минимальное значение**

In [59]:
import numpy as np

def solution(m1, m2):
    result = np.maximum(m1, m2).min()
    return result

m1 = np.random.randint(0, 10, 10)
m2 = np.random.randint(0, 10, 10)
print(m1)
print(m2)
solution(m1, m2)

[7 7 8 0 2 3 4 8 9 6]
[1 0 5 6 2 2 5 0 6 9]


2

**На вход подаётся одномерный массив. Найдите среднее значение.**

In [60]:
import numpy as np

def solution(m1):
    result = m1.mean()
    return result