**На вход подается матрица. Посчитайте минимальные значения по каждому столбцу**

In [1]:
import numpy as np

def solution(m2d):
    result = m2d.min(axis=0)
    return result

m2d = np.random.randint(0, 10, (3, 5))
print(m2d)
solution(m2d)

[[7 7 8 8 2]
 [4 7 1 1 8]
 [3 6 7 3 3]]


array([3, 6, 1, 1, 2])

**На вход подается матрица. Посчитайте максимальные значения по каждой строке**

In [2]:
import numpy as np

def solution(m2d):
    result = m2d.max(axis=1)
    return result

m2d = np.random.randint(0, 10, (3, 5))
print(m2d)
solution(m2d)

[[6 1 7 9 8]
 [3 1 3 6 6]
 [3 7 5 7 2]]


array([9, 6, 7])

**Ранее пройденная задача, но попробуем решить ее снова:**

На вход подается одномерный массив в котором хранится информация о количестве картофеля на каждом складе (всего 4 склада). Посчитайте для каждого склада, сколько процентов картофеля от общего количества хранится на каждом складе.

Общее количество картофеля на всех складах (определите сами через функцию).

Не забудьте что каждое значение надо умножить на 100.

Округлять значения не требуется! Знак процента тоже добавлять не следует. Просто выполните арифметические операции.

In [4]:
import numpy as np

def solution(arr):
    result = arr / arr.sum() * 100
    return result


arr = np.random.randint(200, 400, 4)
print(arr)
solution(arr)

[354 371 331 215]


array([27.85208497, 29.18961448, 26.04248623, 16.91581432])

**Вам передан одномерный массив. Если значение меньше или равно нулю, то замените его на нуль. Если значение больше нуля, то замените на 1.**



In [6]:
import numpy as np

def solution(arr):
    res = np.where(arr <= 0, 0, 1)
    return res

arr = np.random.randint(-10, 10, 10)
print(arr)
print(solution(arr))

[-10   3  -6  -3  -6   6  -2  -9   7  -1]
[0 1 0 0 0 1 0 0 1 0]


**Вам передана матрица. Если значение меньше или равно нулю, то замените его на нуль. Остальное не трогать**

In [8]:
import numpy as np

def solution(m2d):
    res = np.where(m2d <= 0, 0, m2d)
    return res


m2d = np.random.randint(-9, 10, (3, 4))
print(m2d)
print(solution(arr))

[[ 9 -2  7 -1]
 [ 6  5 -3  2]
 [-1  6 -8 -7]]
[0 3 0 0 0 6 0 0 7 0]


**Вам передана матрица. Если значение меньше нуля, то возьмите его по модулю. Если значение больше нуля, то извлеките из него квадратный корень.**



In [13]:
import numpy as np

def solution(m2d):
    res = np.where(m2d < 0, np.abs(m2d), np.sqrt(m2d))
    return res


m2d = np.random.randint(-9, 10, (4, 5))
print(m2d)
print(solution(m2d))

[[ 9  5  6  3  5]
 [ 5  1  7  1 -2]
 [-1  4  1  0  1]
 [-4  1  7  9 -7]]
[[3.         2.23606798 2.44948974 1.73205081 2.23606798]
 [2.23606798 1.         2.64575131 1.         2.        ]
 [1.         2.         1.         0.         1.        ]
 [4.         1.         2.64575131 3.         7.        ]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: RuntimeWarning: invalid value encountered in sqrt
  after removing the cwd from sys.path.


**На вход подается матрица. Для каждого столбца определите индекс строки в которой содержится минимальное значение.**

In [14]:
import numpy as np

def solution(m2d):
    res = m2d.argmin(axis=0)
    return res


m2d = np.random.randint(0, 100, (4, 5))
print(m2d)
solution(m2d)

[[50 12 50 44 71]
 [56  1 34 40 92]
 [35 99 40 78 26]
 [29 87 16 72 58]]


array([3, 1, 3, 1, 2])

**На вход подается матрица. Для каждой строки определите индекс столбца в котором содержится максимальное значение.**

In [15]:
import numpy as np

def solution(m2d):
    return m2d.argmax(axis=1)


m2d = np.random.randint(0, 10, (4, 5))
print(m2d)
solution(m2d)

[[3 0 0 0 4]
 [1 1 8 3 7]
 [4 7 7 7 8]
 [7 3 6 9 1]]


array([4, 2, 4, 3])