In [7]:
import numpy as np

bool1 = np.array([True, True, False, True])
bool2 = np.array([True, True, True, True])
bool3 = np.array([False, False, False, False])

#**Есть ли хотя бы одно True?**

In [9]:
bool1.any(), bool2.any(), bool3.any()

(True, True, False)

In [14]:
user_data = np.array([350, 200, 100, 1000, 500])
mask = user_data > 800
mask

array([False, False, False,  True, False])

In [15]:
mask.any()

True

#**Все ли значения в положительны?**

In [16]:
mask.sum()

1

In [17]:
mask.sum == len(bool1)

False

In [20]:
bool1.all(), bool2.all(), bool3.all()

(False, True, False)

#**Сортировка**

In [22]:
m1 = np.array([1, 2, 3, -8, 2, 7, 3])
m1

array([ 1,  2,  3, -8,  2,  7,  3])

**Метод sort ничего не возращает, она сортирует исходный объект**

In [24]:
m1.sort()
m1

array([-8,  1,  2,  2,  3,  3,  7])

**Сортировка двумерных массивов**

In [25]:
m2d = np.random.randint(0, 10, (3, 4))
m2d

array([[3, 4, 6, 0],
       [4, 3, 1, 5],
       [0, 2, 6, 9]])

In [27]:
m2d.sort()
m2d

array([[0, 3, 4, 6],
       [1, 3, 4, 5],
       [0, 2, 6, 9]])

In [28]:
m2d = np.random.randint(0, 10, (3, 4))
m2d

array([[3, 8, 9, 6],
       [4, 0, 9, 3],
       [0, 6, 1, 6]])

- Сортировка по столбцам

In [30]:
m2d.sort(axis=0)
m2d

array([[0, 0, 1, 3],
       [3, 6, 9, 6],
       [4, 8, 9, 6]])

#**Уникальные значения**

In [31]:
names = np.array(['Ivan', 'Andrey', 'Sergei', 'Roman', 'Andrey', 'Ivan'])
names

array(['Ivan', 'Andrey', 'Sergei', 'Roman', 'Andrey', 'Ivan'], dtype='<U6')

In [33]:
unames = np.unique(names)
unames

array(['Andrey', 'Ivan', 'Roman', 'Sergei'], dtype='<U6')

In [34]:
len(unames)

4

In [35]:
m1 = np.array([1, 2, 3, 1, 0, 1])
np.unique(m1)

array([0, 1, 2, 3])

In [37]:
names = np.array(['Ivan', 'Andrey', 'Sergei', 'Roman', 'Andrey', 'Ivan'])
names == 'Roman'

array([False, False, False,  True, False, False])

In [38]:
(names == 'Roman') | (names == 'Andrey')

array([False,  True, False,  True,  True, False])

In [39]:
np.in1d(names, ['Ivan', 'Andrey'])

array([ True,  True, False, False,  True,  True])

#**Линейная алгебра**

In [41]:
m = np.array([[1, 5, 0], [6, 2, 0], [-2, 4, 8]])
m

array([[ 1,  5,  0],
       [ 6,  2,  0],
       [-2,  4,  8]])

In [42]:
m.T

array([[ 1,  6, -2],
       [ 5,  2,  4],
       [ 0,  0,  8]])

In [43]:
np.dot(m.T, m)

array([[ 41,   9, -16],
       [  9,  45,  32],
       [-16,  32,  64]])

In [44]:
np.linalg.det(m)

-224.00000000000014

In [45]:
np.linalg.inv(m)

array([[-0.07142857,  0.17857143,  0.        ],
       [ 0.21428571, -0.03571429,  0.        ],
       [-0.125     ,  0.0625    ,  0.125     ]])

In [47]:
np.diag(m)

array([1, 2, 8])

In [48]:
np.triu(m)

array([[1, 5, 0],
       [0, 2, 0],
       [0, 0, 8]])

In [50]:
np.triu(m).sum()

16

In [51]:
np.tril(m)

array([[ 1,  0,  0],
       [ 6,  2,  0],
       [-2,  4,  8]])

In [52]:
np.tril(m).sum()

19

In [53]:
np.trace(m)

11

In [55]:
m

array([[ 1,  5,  0],
       [ 6,  2,  0],
       [-2,  4,  8]])

In [58]:
np.diag(m, k=1), np.diag(m, k=2)

(array([5, 0]), array([0]))

In [59]:
np.diag(m, k=-1), np.diag(m, k=-2)

(array([6, 4]), array([-2]))

#**Генерация массивов**

In [60]:
np.random.randint(1, 10, size=5)

array([3, 6, 7, 5, 4])

In [61]:
np.random.randint(1, 10, size=(3, 5))

array([[5, 5, 9, 7, 6],
       [9, 2, 3, 3, 3],
       [7, 5, 9, 9, 4]])

**На вход подаётся одномерный массив типа np.bool. Функция должна вернуть True если все значения в массиве равны False. Иначе функция должна вернуть False.**


In [65]:
import numpy as np

def solution(m1d):
    return m1d.sum() == 0


m1d = np.random.choice(a=[False, True], size=10)
solution(m1d)

False

**На вход подаётся матрица. Посчитайте сумму элементов верхнего треугольника:**



In [68]:
import numpy as np

def solution(m2d):
    return np.triu(m2d).sum()

m2d = np.random.randint(0, 10, (5, 5))
print(m2d)
solution(m2d)

[[8 2 4 3 4]
 [6 2 8 9 6]
 [6 7 6 6 9]
 [8 3 1 8 7]
 [8 2 6 8 7]]


89

**На вход подаётся одномерный массив. Посчитайте количество уникальных значений.**

In [69]:
import numpy as np

def solution(m1d):
    return len(np.unique(m1d))

m1d = np.random.randint(0, 10, 10)
print(m1d)
solution(m1d)

[2 2 3 0 3 7 5 7 5 7]


5