In [2]:
import numpy as np

m = np.random.randint(0, 10, 10)
m

array([4, 0, 5, 0, 4, 7, 9, 6, 1, 2])

In [3]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
# разбросанный range
np.random.permutation(10)

array([9, 8, 6, 2, 7, 1, 3, 5, 4, 0])

In [9]:
# меняет порядок в массиве
m1 = np.arange(10)
np.random.shuffle(m1)
m1

array([3, 7, 8, 5, 1, 4, 6, 9, 2, 0])

In [10]:
# функция, которая генерирует значения из нормального распределения
np.random.randn(10)

array([ 0.21247029,  1.37349533, -1.52929265, -0.01326415,  0.21275389,
        1.07306126, -0.68118124,  2.13875528, -0.62459531, -0.42367263])

In [11]:
np.random.randn(2, 5)

array([[-0.9877296 , -0.88050498, -0.44659771,  0.75917178,  0.77492089],
       [ 1.65991764, -1.03317208,  1.44131974,  0.99040806,  1.6564553 ]])

In [12]:
m1 = np.arange(10)
m1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.save('myarray', m1)

In [15]:
np.load('myarray.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
m2 = m1 * 10
m2

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [18]:
np.savez('arrays', name1=m1, name2=m2)

In [22]:
xfile = np.load('arrays.npz')

In [23]:
xfile['name1']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
xfile['name2']

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
np.savez_compressed('compressed', key1=m1, key2=m2)
np.load('compresed.npz')