**Создайте массив заполненный нулями у которого shape = (2, 5)**

In [1]:
import numpy as np

def solution():
    arr = np.zeros((2, 5))
    return arr

solution()

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

**Создайте массив заполненный единицами у которого 5 строк и 8 столбцов (5 вложенных массивов длинной 8)**

In [3]:
import numpy as np

def solution():
    arr = np.ones((5, 8))
    return arr

solution()

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

**Создайте одномерный numpy массив со значениями 0, 1, 2, .... 99 (диапазон значений от 0 до 99)**

In [4]:
import numpy as np

def solution():
    arr = np.arange(100)
    return arr

solution()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

**Создайте двумерный массив размером 5 х 2, который полностью будет заполнен значением 'G'**


In [5]:
import numpy as np

def solution():
    arr = np.full((5, 2), 'G')
    return arr

solution()

array([['G', 'G'],
       ['G', 'G'],
       ['G', 'G'],
       ['G', 'G'],
       ['G', 'G']], dtype='<U1')