#**Типы данных**

Для целых чисел (со знаком):

- int8, int16, int32, int64  - чем больше число после слова int, тем больше памяти будет потрачено на хранение каждого значения массива.

**Например, если у нас одномерный массив типа int64 в котором хранится 1 млн. значений, то в памяти компьютера будет занято: 64 * 1млн = 64 млн бит = 8 млн байт = 7 812 КБ = 7.6 МБ. А если изменить на int8, то 0.95 МБ (меньше 1 МБ).**

 

Для целых чисел (без знака):

- uint8, uint16, uint32, uint64 

 

 Для чисел с плавающей точкой:

- float16, float32, float64

 

Для комплексных чисел: 
  - complex64, complex128, complex256

 

 Другие типы данных:

- bool - логический тип данных (для хранения True, False)

- object - любой питоновский объект

- string_ - строка в кодировке ASCII (1 байт на каждый символ)

- unicode_ -строка в кодировке unicode (количество байт зависит от платформы)

In [1]:
import numpy as np

In [3]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr.dtype

dtype('int64')

In [5]:
arr1 = np.array([1, 2, 3, 4, 5], dtype=np.float64)
arr1

array([1., 2., 3., 4., 5.])

In [6]:
arr1.dtype

dtype('float64')

#**Изменение типа данных**

**Функция astype**


Функция astype выполнит преобразование типов и вернет новый массив с новым типом данных.

In [8]:
arr2 = arr1.astype(np.int64)
arr2.dtype, arr1.dtype

(dtype('int64'), dtype('float64'))

In [11]:
arr1 = np.array([1.1, 2.2, 3.3, 4.1, 5.7], dtype=np.float64)
arr1

array([1.1, 2.2, 3.3, 4.1, 5.7])

In [12]:
arr2 = arr1.astype(np.int32)
arr2

array([1, 2, 3, 4, 5], dtype=int32)

Если вы поменяете тип данных с float_ на int_, то numpy отрежет десятичную часть от каждого числа и оставит только целую. Округления не будет! Округление делается по другому.

**Преобразование из строки в число**

Во время преобразования из строки в число может произойти ошибка. Скорее всего она вызвана тем, что где-то в массиве нет числа вовсе или число записано с ошибкой. На практике бывает и то и другое сразу.

In [13]:
arr1 = np.array(['1.2', '2.6', '3.5', '4.8'])
arr1

array(['1.2', '2.6', '3.5', '4.8'], dtype='<U3')

In [14]:
arr2 = arr1.astype(np.float64)
arr2

array([1.2, 2.6, 3.5, 4.8])

In [15]:
arr2.dtype

dtype('float64')

In [16]:
arr1 = np.array(['1.2', '2.6', '3.5', '4.8!'])
arr2 = arr1.astype(np.float64)
arr2

ValueError: ignored

In [17]:
arr1 = np.array(['1.2', '2.6', '3.5', ''])
arr2 = arr1.astype(np.float64)
arr2

ValueError: ignored

In [18]:
m1 = np.arange(10)
m2 = np.array([1.1, 1.2, 1.3], dtype=np.float64)

In [19]:
m1.astype(np.float64)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [20]:
m1.astype(m2.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [21]:
m1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#**Арифметические операции**

In [22]:
lst = [1, 2, 3, 4]
lst = 2 * lst
lst

[1, 2, 3, 4, 1, 2, 3, 4]

In [24]:
lst = [1, 2, 3, 4]
lst = [2 * x for x in lst]
lst

[2, 4, 6, 8]

In [25]:
m1 = np.array([1, 2, 3, 4])
m1 * 2

array([2, 4, 6, 8])

In [26]:
m1 * m1

array([ 1,  4,  9, 16])

In [27]:
lst + 1

TypeError: ignored

In [32]:
m1

array([1, 2, 3, 4])

In [30]:
m1 + 1

array([2, 3, 4, 5])

In [31]:
1 - m1

array([ 0, -1, -2, -3])

In [33]:
1 / m1

array([1.        , 0.5       , 0.33333333, 0.25      ])

In [34]:
m1**2

array([ 1,  4,  9, 16])

**Арифметические операции с многомерными массивами**

In [37]:
m2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
m2d

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [38]:
m2d + 1

array([[2, 3, 4, 5],
       [6, 7, 8, 9]])

In [39]:
m2d + 1.5

array([[2.5, 3.5, 4.5, 5.5],
       [6.5, 7.5, 8.5, 9.5]])

In [40]:
m2d * m2d

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

**Поэлементное сравнение**

In [42]:
temp1006 = [36.6, 35.5, 36.8]
temp1106 = [36.6, 36.6, 36.6]

temp1106 > temp1006

True

In [43]:
m1_temp1006 = np.array(temp1006)
m1_temp1106 = np.array(temp1106)

m1_temp1106 > m1_temp1006

array([False,  True, False])

In [44]:
m3 = m1_temp1106 > m1_temp1006
m3.dtype

dtype('bool')

#**Доступ к элементам массива**

**для доступа к одному элементу массива указываем индекс этого элемента в квадратных скобках:**

    m1[ИНДЕКС]

**для получения доступа к нескольким элементам указываем диапазон через двоеточие:**

    m1[индекс_первого_элемента : индекс_последнего_элемента]   
такая конструкция называется слайсингом (от англ. slice)

In [45]:
m1 = np.arange(10)
m1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
m1[4]

4

In [47]:
m1[4] = 0
m1

array([0, 1, 2, 3, 0, 5, 6, 7, 8, 9])

In [48]:
m1[4] = 4
m1[3:6]

array([3, 4, 5])

In [49]:
m1[3:6] = 0
m1

array([0, 1, 2, 0, 0, 0, 6, 7, 8, 9])

In [51]:
m1[3:6] = [3, 4, 5]
m1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

**Запоминаем важный факт, который не совсем очевиден.**

Если мы делаем слайс, например, m1[3:5], а затем присваиваем этот кусочек в новую переменную, то в новой переменной будет лежать ваш кусочек, который всё еще ссылается на основной массив. 

In [53]:
m2 = m1[3:6]
m2[0] = 0
m2

array([0, 4, 5])

In [54]:
m1

array([0, 1, 2, 0, 4, 5, 6, 7, 8, 9])

**Напишите функцию, которая на основе существующего списка создает numpy массив с типом float64**

In [55]:
import numpy as np

def solution(lst):
    arr = np.array(lst, dtype=np.float64)
    return arr

solution([1, 2, 3])

array([1., 2., 3.])

**К вам в распоряжение поступает массив arr с типом float64. Преобразуйте, пожалуйста, в int32**



In [58]:
import numpy as np

def solution(arr):
    arr = arr.astype(np.int32)
    return arr

solution(np.array([1, 2, 3], dtype=np.float64)).dtype

dtype('int32')