**На вход подается одномерный массив со значениями от 0 до 5 (включительно). Примените некоторую операцию  чтобы на выходе получился массив со значениями 1000, 1001....1005**



In [1]:
import numpy as np

def solution(arr):
    arr = arr + 1000
    return arr

solution(np.arange(6))

array([1000, 1001, 1002, 1003, 1004, 1005])

**На вход подается одномерный массив в котором хранится информация о количестве картофеля на каждом складе (всего 4 склада). Посчитайте для каждого склада, сколько процентов картофеля от общего количества хранится на каждом складе.**

- Общее количество картофеля на всех складах 115 кг.

- Не забудьте что каждое значение надо умножить на 100.

- Округлять значения не требуется! Знак процента тоже добавлять не следует. Просто выполните арифметические операции.

In [2]:
import numpy as np

def solution(arr):
    res = arr / np.sum(arr) * 100
    return res

solution(np.array([35, 15, 25, 40]))

array([30.43478261, 13.04347826, 21.73913043, 34.7826087 ])

**Выполните действия**

1. Создайте одномерный массив со значениями в диапазоне от 0 до 10 (включительно). 

2. Создайте второй одномерный массив со значениями в диапазоне от 10 до 20 (включительно). 

3. Вычтите из второго массива первый. 

Проверьте каждое значение получившегося массива на равенство значению 10. Результат сравнения верните в отдельном numpy массиве.

In [31]:
import numpy as np

def solution():
    arr1 = np.arange(0,11)
    arr2 = np.arange(10, 21)
    res =  arr2 - arr1 == 10
    return False if False in res else True

solution()

True

**Во входящем массиве arr содержится информация о водителях, которые превысили скорость на некотором участке дороги. Определите насколько каждый водитель превысил скорость, если допустимая скорость равна 80. Результаты представьте в отдельном numpy массиве**

In [35]:
import numpy as np

def solution(arr):
    arr = arr - 80
    return arr

arr = np.array(input().split(), dtype=np.int16)
solution(arr)

82 90 180 250


array([  2,  10, 100, 170], dtype=int16)

**На вход вашей функции подается некоторый одномерный массив. Предполагается, что там лежат числа с плавающей точкой, но записаны они как строка. Выполните сложение элементов с индексами 1 и 3. На выходе ваша функция должна вернуть число (сумма двух элементов массива).**

In [36]:
import numpy as np

def solution(arr):
    arr = arr.astype(np.float64)
    return arr[1] + arr[3]

arr = np.array(input().split())
solution(arr)

12.5 6 7.8 3.4


9.4

**На вход вашей функции подается два одномерных массива. Сложите первые два элемента первого массива с последними двумя элементами второго массива (поэлементно). На выходе должен получится новый одномерный массив, который будет хранить два значения**

In [40]:
import numpy as np

def solution(arr1, arr2):
    arr = arr1[:2] + arr2[-2:]
    return arr

arr1 = np.arange(10)
arr2 = np.arange(10)
solution(arr1, arr2)

array([ 8, 10])

**На вход подается некоторый одномерный массив. Занулите первые 3 элемента.**



In [43]:
import numpy as np

def solution(arr):
    arr[0:3] = 0
    return arr

arr = np.arange(10)
solution(arr)

array([0, 0, 0, 3, 4, 5, 6, 7, 8, 9])