**На вход подается одномерный массив, преобразуйте его в матрицу с 5 строками и 6 столбцами**

In [6]:
import numpy as np

def solution(arr):
    return arr.reshape(5, 6)

**На вход подается одномерный массив, преобразуйте его в трехмерный массив, где каждая матрица будет размером 4х5 и таких матриц должно быть 10**



In [7]:
import numpy as np

def solution(arr):
    return arr.reshape(10, 4, 5)

**На вход подается двумерная матрица. Вытяните из нее последние три строки, но так чтобы строки были расположены в обратном порядке.**



In [10]:
import numpy as np

def solution(arr):
    indx = np.arange(len(arr) - 3, len(arr))[::-1]
    return arr[indx]


arr = np.random.randint(0, 10, (4, 5))
print(arr)
print(solution(arr))

[[7 4 1 6 8]
 [2 9 7 0 1]
 [0 2 2 6 8]
 [9 8 4 6 2]]
[[9 8 4 6 2]
 [0 2 2 6 8]
 [2 9 7 0 1]]


**На вход подается двумерная матрица. Вытяните из нее последние три строки, но так чтобы строки были расположены в обратном порядке. Затем возьмите только последние два столбца.**





In [12]:
import numpy as np

def solution(arr):
    indx = np.arange(len(arr) - 3, len(arr))[::-1]
    return arr[indx][:, -2:]

arr = np.random.randint(0, 10, (4, 5))
print(arr)
print(solution(arr))

[[4 1 8 1 7]
 [4 8 1 9 0]
 [9 7 2 9 9]
 [4 5 1 6 2]]
[[6 2]
 [9 9]
 [9 0]]


**На вход подается двумерная матрица размером 5х5. Преобразуйте ее в одномерный массив.**

In [16]:
import numpy as np

def solution(arr):
    return arr.reshape(-1)

arr = np.random.randint(0, 10, (4, 5))
print(arr)
print(solution(arr))

[[6 7 7 9 9]
 [8 2 8 5 9]
 [1 2 7 0 6]
 [0 8 8 6 8]]
[6 7 7 9 9 8 2 8 5 9 1 2 7 0 6 0 8 8 6 8]


**На вход подается трехмерная матрица размером 6х5х5. Преобразуйте ее в одномерный массив.**

In [17]:
import numpy as np

def solution(arr):
    return arr.reshape(-1)

arr = np.random.randint(0, 10, (6, 5, 5))
print(arr)
print(solution(arr))

[[[8 2 3 2 9]
  [4 7 9 9 4]
  [6 9 1 6 2]
  [8 0 7 6 4]
  [2 1 1 8 3]]

 [[6 3 0 0 9]
  [3 3 2 3 4]
  [7 3 3 5 0]
  [0 1 8 5 9]
  [0 6 4 0 7]]

 [[6 6 2 2 6]
  [9 0 3 1 5]
  [3 1 9 0 3]
  [7 7 5 1 2]
  [3 3 5 5 4]]

 [[0 4 1 5 3]
  [2 9 6 0 0]
  [3 2 5 6 0]
  [8 9 3 4 6]
  [8 3 5 1 1]]

 [[6 7 1 9 5]
  [1 6 0 7 4]
  [2 6 8 8 7]
  [6 4 8 0 6]
  [6 7 0 2 1]]

 [[4 5 9 1 6]
  [8 2 9 2 1]
  [7 7 3 8 2]
  [4 7 3 9 3]
  [2 4 3 3 9]]]
[8 2 3 2 9 4 7 9 9 4 6 9 1 6 2 8 0 7 6 4 2 1 1 8 3 6 3 0 0 9 3 3 2 3 4 7 3
 3 5 0 0 1 8 5 9 0 6 4 0 7 6 6 2 2 6 9 0 3 1 5 3 1 9 0 3 7 7 5 1 2 3 3 5 5
 4 0 4 1 5 3 2 9 6 0 0 3 2 5 6 0 8 9 3 4 6 8 3 5 1 1 6 7 1 9 5 1 6 0 7 4 2
 6 8 8 7 6 4 8 0 6 6 7 0 2 1 4 5 9 1 6 8 2 9 2 1 7 7 3 8 2 4 7 3 9 3 2 4 3
 3 9]
