**reshape меняет только форму**

In [2]:
import numpy as np

m1 = np.arange(50)
m1.reshape(5, 2, 5)

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]]])

In [2]:
m2 = m1.reshape(5, 2, 5)
m2

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]]])

In [4]:
m2[0] = 0
m2

array([[[ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]]])

In [5]:
m1

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

#**Транспонирование**

In [6]:
m1 = np.arange(21).reshape(3, 7)
m1

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20]])

In [7]:
m1.T

array([[ 0,  7, 14],
       [ 1,  8, 15],
       [ 2,  9, 16],
       [ 3, 10, 17],
       [ 4, 11, 18],
       [ 5, 12, 19],
       [ 6, 13, 20]])

In [11]:
from numpy.core.fromnumeric import transpose
m2 = m1.transpose()
m2

array([[ 0,  7, 14],
       [ 1,  8, 15],
       [ 2,  9, 16],
       [ 3, 10, 17],
       [ 4, 11, 18],
       [ 5, 12, 19],
       [ 6, 13, 20]])

In [12]:
m2[0] = 0
m2

array([[ 0,  0,  0],
       [ 1,  8, 15],
       [ 2,  9, 16],
       [ 3, 10, 17],
       [ 4, 11, 18],
       [ 5, 12, 19],
       [ 6, 13, 20]])

In [13]:
m1

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 0,  8,  9, 10, 11, 12, 13],
       [ 0, 15, 16, 17, 18, 19, 20]])

In [15]:
m1 = np.arange(21).reshape(3, 7)
m1

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20]])

**Без использования Numpy**

In [17]:
res = []
lst = []

for j in range(len(m1[0])):
    for i in range(len(m1)):
        print(m1[i][j],end=' ')
    print()

0 7 14 
1 8 15 
2 9 16 
3 10 17 
4 11 18 
5 12 19 
6 13 20 


#**Встроенные функции Numpy**

In [19]:
m1 = np.array([2, 4, 6, 8])
m1

array([2, 4, 6, 8])

In [20]:
m2 = m1**2
m2

array([ 4, 16, 36, 64])

In [22]:
np.sqrt(m2).astype(np.int8)

array([2, 4, 6, 8], dtype=int8)

In [23]:
m1 = np.array([2, -4, -6, 8])
np.abs(m1)

array([2, 4, 6, 8])

In [24]:
m1 = np.array([2.1, 2.7, 2.5, 2.7])
np.round(m1)

array([2., 3., 2., 3.])

In [25]:
np.ceil(m1)

array([3., 3., 3., 3.])

In [26]:
np.floor(m1)

array([2., 2., 2., 2.])

In [27]:
m1 = np.array([2.1, 2.7, 2.5, 2.7, np.nan])
m1

array([2.1, 2.7, 2.5, 2.7, nan])

In [28]:
len(m1)

5

In [29]:
np.isnan(m1)

array([False, False, False, False,  True])

In [30]:
np.round(m1)

array([ 2.,  3.,  2.,  3., nan])

In [4]:
m1 = np.array([1, -2, 3, -4])
np.abs(m1, out=m1)
m1

array([1, 2, 3, 4])

**Унарные функкции, те которые возращают одно значение, принимая один массив**

**Бинарные функции, те которые возращают одно значение, принимая два массива**

In [6]:
m1 = np.array([1, 2, 3, 4])
m2 = np.array([0, 3, 1, 6])

In [7]:
np.maximum(m1, m2)

array([1, 3, 3, 6])

In [8]:
np.minimum(m1, m2)

array([0, 2, 1, 4])

In [9]:
np.add(m1, m2)

array([ 1,  5,  4, 10])

In [10]:
m1 + m2

array([ 1,  5,  4, 10])

In [11]:
m1 - m2

array([ 1, -1,  2, -2])

In [13]:
np.subtract(m1, m2)

array([ 1, -1,  2, -2])

In [14]:
np.multiply(m1, m2)

array([ 0,  6,  3, 24])

In [16]:
res = m1 / m2

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


In [17]:
res

array([       inf, 0.66666667, 3.        , 0.66666667])

In [20]:
np.isinf(res)

array([ True, False, False, False])

In [21]:
np.divide(m1, m2)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 0.66666667, 3.        , 0.66666667])