https://www.youtube.com/watch?v=POgD3xN5Q6Y&list=PLA0M1Bcd0w8zmegfAUfFMiACPKfdW4ifD&index=5&t=573s

In [ ]:
import numpy as np

In [ ]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a.shape = 2, 5
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
#Создали новое представление массива как одномерный список
b = a.reshape(10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#Прежнее представление осталось без изменений
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

Массивы a и b ссылаются на один и тот же объект. При этом имеют разные представления

In [ ]:
b[0] = -1
b

array([-1,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [ ]:
a.shape = 5, 2
a

array([[-1,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9]])

In [ ]:
# -1 - Пусть здесь будет столько элементов сколько останется
# 5 - число столбцов
a.shape = -1, 5
a

array([[-1,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9]])

In [ ]:
#Получение вектора столбца
b.reshape(-1, 1)

array([[-1],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9]])

In [ ]:
#Матрица с двумя осями
b.reshape(1, -1)

array([[-1,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [ ]:
#Вектор с одной осью
b

array([-1,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [ ]:
#Преобразование многомерного массива в одномерный
c = a.ravel()
c

array([-1,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [ ]:
#Представление массива а остается неизменным
a

array([[-1,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9]])

In [ ]:
#Изменение массива, чтобы он стал одномерным
a.shape = -1
a

array([-1,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [ ]:
#resize меняет представление текущего массива
a.resize(2, 5)
a

array([[-1,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9]])

In [ ]:
a.resize(3, 3, refcheck=False)
a

array([[-1,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8]])

In [ ]:
a.resize(4, 5, refcheck=False)
a

array([[-1,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  0],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0]])

In [ ]:
#Транспонирование
b = a.T
b

array([[-1,  5,  0,  0],
       [ 1,  6,  0,  0],
       [ 2,  7,  0,  0],
       [ 3,  8,  0,  0],
       [ 4,  0,  0,  0]])

In [ ]:
x = np.arange(1, 10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#У вектора Х одна ось
#чтобы транспонировать, нужно добавить ось
x.T

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#Добавили ось
x.shape = 1, -1

In [ ]:
x.T

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [ ]:
#Добавление и удаление осей
x_test = np.arange(32).reshape(8, 2, 2)
x_test

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27]],

       [[28, 29],
        [30, 31]]])

In [ ]:
x.shape

(1, 9)

In [ ]:
x_test.shape

(8, 2, 2)

In [ ]:
#добавляем ось
#np,expend_dims составляет представление массива, добавляя новую ось
#копирования данных не происходит
x_test4 = np.expand_dims(x_test, axis=0)

In [ ]:
x_test4.shape

(1, 8, 2, 2)

In [ ]:
x_test4[0, 0, 0, 0] = -100
x_test4

array([[[[-100,    1],
         [   2,    3]],

        [[   4,    5],
         [   6,    7]],

        [[   8,    9],
         [  10,   11]],

        [[  12,   13],
         [  14,   15]],

        [[  16,   17],
         [  18,   19]],

        [[  20,   21],
         [  22,   23]],

        [[  24,   25],
         [  26,   27]],

        [[  28,   29],
         [  30,   31]]]])

In [ ]:
x_test4.shape

(1, 8, 2, 2)

In [ ]:
#Добавили новый элемент к существующему массиву
a = np.append(x_test4, x_test4, axis = 0)
a.shape

(2, 8, 2, 2)

In [ ]:
#Удаление оси
b = np.delete(a, 0, axis=0)
b.shape

(1, 8, 2, 2)

In [ ]:
#Добавление к многомерному массиву последнюю ось
b = np.expand_dims(x_test4, axis=-1)
b.shape

(1, 8, 2, 2, 1)

In [ ]:
#Удаление всех осей в которых один элемент
c = np.squeeze(b)
c.shape

(8, 2, 2)

In [ ]:
#Удаление строго одной оси
c = np.squeeze(b, axis=0)
c.shape

(8, 2, 2, 1)

In [ ]:
#Добавление оси
a = np.arange(1, 10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
b = a[np.newaxis, :]
b.shape

(1, 9)

In [ ]:
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [ ]:
b = a[:, np.newaxis]
b

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [ ]:
b = a[np.newaxis, :, np.newaxis]
b

array([[[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]]])

In [ ]:
b.shape

(1, 9, 1)